/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ImagePackage;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author olu
 */
public class User_Manual extends javax.swing.JFrame {

    int pageCounter;

    /**
     * Creates new form User_Manual
     */
    public User_Manual() {
        initComponents();
        pageCounter = 1;
        Image manual;
        try {
            manual = ImageIO.read(getClass().getResource("IGPA_User_Manual_pagenumber01.jpg"));
            ImageIcon logo = new ImageIcon(ScaledImage(manual, 617, 585));
            picLabel.setIcon(logo);
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        previousButton = new javax.swing.JButton();
        gotoButton = new javax.swing.JButton();
        pageField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        tableofcontentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("USER MANUAL");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        previousButton.setBackground(new java.awt.Color(255, 255, 255));
        previousButton.setFont(new java.awt.Font("Forte", 1, 11)); // NOI18N
        previousButton.setForeground(new java.awt.Color(204, 102, 0));
        previousButton.setText("PREVIOUS");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        gotoButton.setBackground(new java.awt.Color(255, 255, 255));
        gotoButton.setFont(new java.awt.Font("Forte", 1, 11)); // NOI18N
        gotoButton.setForeground(new java.awt.Color(204, 102, 0));
        gotoButton.setText("GO-TO PAGE");
        gotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoButtonActionPerformed(evt);
            }
        });

        pageField.setFont(new java.awt.Font("Forte", 0, 11)); // NOI18N
        pageField.setForeground(new java.awt.Color(204, 102, 0));
        pageField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pageFieldKeyTyped(evt);
            }
        });

        nextButton.setBackground(new java.awt.Color(255, 255, 255));
        nextButton.setFont(new java.awt.Font("Forte", 1, 11)); // NOI18N
        nextButton.setForeground(new java.awt.Color(204, 102, 0));
        nextButton.setText("NEXT");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setFont(new java.awt.Font("Forte", 1, 11)); // NOI18N
        homeButton.setForeground(new java.awt.Color(204, 102, 0));
        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        tableofcontentButton.setBackground(new java.awt.Color(255, 255, 255));
        tableofcontentButton.setFont(new java.awt.Font("Forte", 1, 11)); // NOI18N
        tableofcontentButton.setForeground(new java.awt.Color(204, 102, 0));
        tableofcontentButton.setText("TABLE OF CONTENT");
        tableofcontentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableofcontentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previousButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gotoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tableofcontentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(previousButton)
                    .addComponent(pageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gotoButton)
                    .addComponent(homeButton)
                    .addComponent(tableofcontentButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        pageCounter = pageCounter + 1;
        if (pageCounter <= 8 && pageCounter >= 1) {
            Image manual;
            try {
                manual = ImageIO.read(getClass().getResource("IGPA_User_Manual_pagenumber0" + pageCounter + ".jpg"));
                ImageIcon logo = new ImageIcon(ScaledImage(manual, 617, 585));
                picLabel.setIcon(logo);
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "End of Manual Reached", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        pageCounter = pageCounter - 1;
        if (pageCounter <= 8 && pageCounter >= 1) {
            Image manual;
            try {
                manual = ImageIO.read(getClass().getResource("IGPA_User_Manual_pagenumber0" + pageCounter + ".jpg"));
                ImageIcon logo = new ImageIcon(ScaledImage(manual, 617, 585));
                picLabel.setIcon(logo);
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "End of Manual Reached", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        pageCounter = 1;

        Image manual;
        try {
            manual = ImageIO.read(getClass().getResource("IGPA_User_Manual_pagenumber01.jpg"));
            ImageIcon logo = new ImageIcon(ScaledImage(manual, 617, 585));
            picLabel.setIcon(logo);
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_homeButtonActionPerformed

    private void tableofcontentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableofcontentButtonActionPerformed
        pageCounter = 2;

        Image manual;
        try {
            manual = ImageIO.read(getClass().getResource("IGPA_User_Manual_pagenumber02.jpg"));
            ImageIcon logo = new ImageIcon(ScaledImage(manual, 617, 585));
            picLabel.setIcon(logo);
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_tableofcontentButtonActionPerformed

    private void gotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoButtonActionPerformed
        String page = pageField.getText();
        if (page.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Input Page Number", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int pageNumber = Integer.parseInt(page);
        pageCounter = pageNumber;

        if (pageCounter <= 8 && pageCounter >= 1) {
            Image manual;
            try {
                manual = ImageIO.read(getClass().getResource("IGPA_User_Manual_pagenumber0" + pageCounter + ".jpg"));
                ImageIcon logo = new ImageIcon(ScaledImage(manual, 617, 585));
                picLabel.setIcon(logo);
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "End of Manual Reached", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_gotoButtonActionPerformed

    private void pageFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pageFieldKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {

            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_pageFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    private Image ScaledImage(Image img, int w, int h) {
        BufferedImage resizedImage = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h, null);
        g2.dispose();
        return resizedImage;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Manual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gotoButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField pageField;
    private javax.swing.JLabel picLabel;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton tableofcontentButton;
    // End of variables declaration//GEN-END:variables
}
