/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ids;

import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author olu
 */
public class PacketDetailsFrame extends javax.swing.JFrame {

   
    /**
     * Creates new form CourseDetailsFrame
     */
    public PacketDetailsFrame() {
        initComponents();    
//Messages msg = new Messages(); 
        synchronized(IDS.query){
         String[][] Result = IDS.query.RetreiveAllInformation(IDS.TableToView);
          DefaultTableModel model = (DefaultTableModel) PacketDetailsTable.getModel();
model.setRowCount(0); 
if(Result!=null){
    if(IDS.TableToView.equals("TRAFFIC_TABLE")){
   PacketDetailsLabel.setText("RECEIVED PACKETS DETAILS");
        for (int i=0; i<Result.length; i++){ 
     
   model.addRow(new Object[]{i+1, Result[i][1],
       Result[i][2],Result[i][3], Result[i][4],
       Result[i][5],Result[i][6],Result[i][7], Result[i][10],Result[i][9],Result[i][11],Result[i][8]});  
   }
}

else if(IDS.TableToView.equals("SPOOFED_TABLE")){
    PacketDetailsLabel.setText("SPOOFED PACKETS DETAILS");
    for (int i=0; i<Result.length; i++){ 
     
   model.addRow(new Object[]{i+1, Result[i][1],
       Result[i][2],Result[i][3], "---",
       "---", Result[i][4],Result[i][5],Result[i][6],Result[i][7],Result[i][8]});  
   }
}
}
        }       
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PacketDetailsTable = new javax.swing.JTable();
        PacketDetailsLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FRAME DETAILS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        PacketDetailsTable.setBackground(new java.awt.Color(0, 0, 51));
        PacketDetailsTable.setFont(new java.awt.Font("Cambria", 1, 11)); // NOI18N
        PacketDetailsTable.setForeground(new java.awt.Color(255, 255, 255));
        PacketDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "S/N", "SOURCE IP", "SOURCE MAC", "DESTINATION MAC", "INITIAL TTL", "HOP COUNT", "PACKET ID", "PROTOCOL", "CHROMOSOME", "FITNESS", "TIME RECEIVED"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PacketDetailsTable.setSelectionBackground(new java.awt.Color(204, 102, 0));
        jScrollPane1.setViewportView(PacketDetailsTable);
        if (PacketDetailsTable.getColumnModel().getColumnCount() > 0) {
            PacketDetailsTable.getColumnModel().getColumn(0).setMinWidth(45);
            PacketDetailsTable.getColumnModel().getColumn(0).setPreferredWidth(45);
            PacketDetailsTable.getColumnModel().getColumn(0).setMaxWidth(65);
        }

        PacketDetailsLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        PacketDetailsLabel.setForeground(new java.awt.Color(0, 0, 51));
        PacketDetailsLabel.setText("PACKET DETAILS");

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(482, 482, 482)
                .addComponent(PacketDetailsLabel)
                .addContainerGap(512, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(PacketDetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         MessageFormat header = new MessageFormat("PACKET DETAILS FRAME");
 MessageFormat footer = new MessageFormat("Page{0, number, integer}");
 try{
  PacketDetailsTable.print( JTable.PrintMode.FIT_WIDTH, header, footer);
          }
 catch (Exception ex){
     synchronized(IDS.msg){
     IDS.msg.ErrorMessages(""+ex);
     }
 }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacketDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacketDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacketDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacketDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacketDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PacketDetailsLabel;
    private javax.swing.JTable PacketDetailsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
